CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "ApiResource" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(256) NOT NULL,
    "Code" character varying(256),
    "GroupName" character varying(256),
    "RoutePattern" character varying(256),
    "NameSpace" character varying(256),
    "ControllerName" character varying(256),
    "ActionName" character varying(256),
    "RequestMethod" character varying(256),
    "IsDeleted" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedBy" bigint,
    "Remark" text,
    CONSTRAINT "PK_ApiResource" PRIMARY KEY ("Id")
);
COMMENT ON TABLE "ApiResource" IS '';
COMMENT ON COLUMN "ApiResource"."Id" IS '';
COMMENT ON COLUMN "ApiResource"."Name" IS '';
COMMENT ON COLUMN "ApiResource"."Code" IS '';
COMMENT ON COLUMN "ApiResource"."GroupName" IS '';
COMMENT ON COLUMN "ApiResource"."RoutePattern" IS '';
COMMENT ON COLUMN "ApiResource"."NameSpace" IS '';
COMMENT ON COLUMN "ApiResource"."ControllerName" IS '';
COMMENT ON COLUMN "ApiResource"."ActionName" IS '';
COMMENT ON COLUMN "ApiResource"."RequestMethod" IS '';
COMMENT ON COLUMN "ApiResource"."IsDeleted" IS '';
COMMENT ON COLUMN "ApiResource"."CreatedAt" IS '';
COMMENT ON COLUMN "ApiResource"."CreatedBy" IS '';
COMMENT ON COLUMN "ApiResource"."UpdatedAt" IS '';
COMMENT ON COLUMN "ApiResource"."UpdatedBy" IS '';
COMMENT ON COLUMN "ApiResource"."Remark" IS '';

CREATE TABLE "AppConfig" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "AppKey" character varying(64) NOT NULL,
    "AppName" character varying(256) NOT NULL,
    "SecretKey" character varying(256) NOT NULL,
    "Sessionkey" character varying(256) NOT NULL,
    "AccessToken" character varying(256),
    "AccessValidTime" bigint,
    "IsEnabled" boolean NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedBy" bigint,
    "Remark" text,
    CONSTRAINT "PK_AppConfig" PRIMARY KEY ("Id")
);
COMMENT ON TABLE "AppConfig" IS '';
COMMENT ON COLUMN "AppConfig"."Id" IS '';
COMMENT ON COLUMN "AppConfig"."AppKey" IS '';
COMMENT ON COLUMN "AppConfig"."AppName" IS '';
COMMENT ON COLUMN "AppConfig"."SecretKey" IS '';
COMMENT ON COLUMN "AppConfig"."Sessionkey" IS '';
COMMENT ON COLUMN "AppConfig"."AccessToken" IS '';
COMMENT ON COLUMN "AppConfig"."AccessValidTime" IS '';
COMMENT ON COLUMN "AppConfig"."IsEnabled" IS '';
COMMENT ON COLUMN "AppConfig"."IsDeleted" IS '';
COMMENT ON COLUMN "AppConfig"."CreatedAt" IS '';
COMMENT ON COLUMN "AppConfig"."CreatedBy" IS '';
COMMENT ON COLUMN "AppConfig"."UpdatedAt" IS '';
COMMENT ON COLUMN "AppConfig"."UpdatedBy" IS '';
COMMENT ON COLUMN "AppConfig"."Remark" IS '';

CREATE TABLE "AppEventConfig" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "AppId" bigint NOT NULL,
    "Name" character varying(256) NOT NULL,
    "Method" character varying(256),
    "EventCode" character varying(256),
    "HookUrl" character varying(256),
    "Type" integer NOT NULL,
    "IsEnabled" boolean NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedBy" bigint,
    "Remark" text,
    CONSTRAINT "PK_AppEventConfig" PRIMARY KEY ("Id")
);
COMMENT ON TABLE "AppEventConfig" IS '';
COMMENT ON COLUMN "AppEventConfig"."Id" IS '';
COMMENT ON COLUMN "AppEventConfig"."AppId" IS '';
COMMENT ON COLUMN "AppEventConfig"."Name" IS '';
COMMENT ON COLUMN "AppEventConfig"."Method" IS '';
COMMENT ON COLUMN "AppEventConfig"."EventCode" IS '';
COMMENT ON COLUMN "AppEventConfig"."HookUrl" IS '';
COMMENT ON COLUMN "AppEventConfig"."Type" IS '';
COMMENT ON COLUMN "AppEventConfig"."IsEnabled" IS '';
COMMENT ON COLUMN "AppEventConfig"."IsDeleted" IS '';
COMMENT ON COLUMN "AppEventConfig"."CreatedAt" IS '';
COMMENT ON COLUMN "AppEventConfig"."CreatedBy" IS '';
COMMENT ON COLUMN "AppEventConfig"."UpdatedAt" IS '';
COMMENT ON COLUMN "AppEventConfig"."UpdatedBy" IS '';
COMMENT ON COLUMN "AppEventConfig"."Remark" IS '';

CREATE TABLE "AppNotificationConfig" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "AppId" bigint NOT NULL,
    "Name" character varying(256) NOT NULL,
    "Type" integer NOT NULL,
    "Phones" character varying(256),
    "NoticeUrl" character varying(256),
    "IsEnabled" boolean NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedBy" bigint,
    "Remark" text,
    CONSTRAINT "PK_AppNotificationConfig" PRIMARY KEY ("Id")
);
COMMENT ON TABLE "AppNotificationConfig" IS '';
COMMENT ON COLUMN "AppNotificationConfig"."Id" IS '';
COMMENT ON COLUMN "AppNotificationConfig"."AppId" IS '';
COMMENT ON COLUMN "AppNotificationConfig"."Name" IS '';
COMMENT ON COLUMN "AppNotificationConfig"."Type" IS '';
COMMENT ON COLUMN "AppNotificationConfig"."Phones" IS '';
COMMENT ON COLUMN "AppNotificationConfig"."NoticeUrl" IS '';
COMMENT ON COLUMN "AppNotificationConfig"."IsEnabled" IS '';
COMMENT ON COLUMN "AppNotificationConfig"."IsDeleted" IS '';
COMMENT ON COLUMN "AppNotificationConfig"."CreatedAt" IS '';
COMMENT ON COLUMN "AppNotificationConfig"."CreatedBy" IS '';
COMMENT ON COLUMN "AppNotificationConfig"."UpdatedAt" IS '';
COMMENT ON COLUMN "AppNotificationConfig"."UpdatedBy" IS '';
COMMENT ON COLUMN "AppNotificationConfig"."Remark" IS '';

CREATE TABLE "AppWebhookConfig" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "AppId" bigint NOT NULL,
    "Name" character varying(256) NOT NULL,
    "Method" character varying(256),
    "HookUrl" character varying(256),
    "Type" integer NOT NULL,
    "IsEnabled" boolean NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedBy" bigint,
    "Remark" text,
    CONSTRAINT "PK_AppWebhookConfig" PRIMARY KEY ("Id")
);
COMMENT ON TABLE "AppWebhookConfig" IS '';
COMMENT ON COLUMN "AppWebhookConfig"."Id" IS '';
COMMENT ON COLUMN "AppWebhookConfig"."AppId" IS '';
COMMENT ON COLUMN "AppWebhookConfig"."Name" IS '';
COMMENT ON COLUMN "AppWebhookConfig"."Method" IS '';
COMMENT ON COLUMN "AppWebhookConfig"."HookUrl" IS '';
COMMENT ON COLUMN "AppWebhookConfig"."Type" IS '';
COMMENT ON COLUMN "AppWebhookConfig"."IsEnabled" IS '';
COMMENT ON COLUMN "AppWebhookConfig"."IsDeleted" IS '';
COMMENT ON COLUMN "AppWebhookConfig"."CreatedAt" IS '';
COMMENT ON COLUMN "AppWebhookConfig"."CreatedBy" IS '';
COMMENT ON COLUMN "AppWebhookConfig"."UpdatedAt" IS '';
COMMENT ON COLUMN "AppWebhookConfig"."UpdatedBy" IS '';
COMMENT ON COLUMN "AppWebhookConfig"."Remark" IS '';

CREATE TABLE "AsyncTask" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "State" integer NOT NULL,
    "Code" character varying(64) NOT NULL,
    "Data" text NOT NULL,
    "ErrorMessage" text,
    "Result" text,
    "RetryCount" integer NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedBy" bigint,
    "Remark" text,
    CONSTRAINT "PK_AsyncTask" PRIMARY KEY ("Id")
);
COMMENT ON TABLE "AsyncTask" IS '';
COMMENT ON COLUMN "AsyncTask"."Id" IS '';
COMMENT ON COLUMN "AsyncTask"."State" IS '';
COMMENT ON COLUMN "AsyncTask"."Code" IS '';
COMMENT ON COLUMN "AsyncTask"."Data" IS '';
COMMENT ON COLUMN "AsyncTask"."ErrorMessage" IS '';
COMMENT ON COLUMN "AsyncTask"."Result" IS '';
COMMENT ON COLUMN "AsyncTask"."RetryCount" IS '';
COMMENT ON COLUMN "AsyncTask"."IsDeleted" IS '';
COMMENT ON COLUMN "AsyncTask"."CreatedAt" IS '';
COMMENT ON COLUMN "AsyncTask"."CreatedBy" IS '';
COMMENT ON COLUMN "AsyncTask"."UpdatedAt" IS '';
COMMENT ON COLUMN "AsyncTask"."UpdatedBy" IS '';
COMMENT ON COLUMN "AsyncTask"."Remark" IS '';

CREATE TABLE "DownloadItem" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(256) NOT NULL,
    "Extension" character varying(16) NOT NULL,
    "Size" bigint NOT NULL,
    bucket character varying(256) NOT NULL,
    key character varying(256) NOT NULL,
    "StorageType" integer NOT NULL,
    "State" integer NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedBy" bigint,
    "Remark" text,
    CONSTRAINT "PK_DownloadItem" PRIMARY KEY ("Id")
);
COMMENT ON TABLE "DownloadItem" IS '';
COMMENT ON COLUMN "DownloadItem"."Id" IS '';
COMMENT ON COLUMN "DownloadItem"."Name" IS '';
COMMENT ON COLUMN "DownloadItem"."Extension" IS '';
COMMENT ON COLUMN "DownloadItem"."Size" IS '';
COMMENT ON COLUMN "DownloadItem".bucket IS '';
COMMENT ON COLUMN "DownloadItem".key IS '';
COMMENT ON COLUMN "DownloadItem"."StorageType" IS '';
COMMENT ON COLUMN "DownloadItem"."State" IS '';
COMMENT ON COLUMN "DownloadItem"."IsDeleted" IS '';
COMMENT ON COLUMN "DownloadItem"."CreatedAt" IS '';
COMMENT ON COLUMN "DownloadItem"."CreatedBy" IS '';
COMMENT ON COLUMN "DownloadItem"."UpdatedAt" IS '';
COMMENT ON COLUMN "DownloadItem"."UpdatedBy" IS '';
COMMENT ON COLUMN "DownloadItem"."Remark" IS '';

CREATE TABLE "File" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(256) NOT NULL,
    "Type" integer NOT NULL,
    "Size" bigint NOT NULL,
    "Extension" character varying(16) NOT NULL,
    "Url" character varying(1024) NOT NULL,
    "Path" character varying(1024) NOT NULL,
    "StorageType" integer NOT NULL,
    "ContentType" character varying(128) NOT NULL,
    "Hash" character varying(64) NOT NULL,
    "OriginalId" bigint NOT NULL,
    "State" integer NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedBy" bigint,
    "Remark" text,
    CONSTRAINT "PK_File" PRIMARY KEY ("Id")
);
COMMENT ON TABLE "File" IS '';
COMMENT ON COLUMN "File"."Id" IS '';
COMMENT ON COLUMN "File"."Name" IS '';
COMMENT ON COLUMN "File"."Type" IS '';
COMMENT ON COLUMN "File"."Size" IS '';
COMMENT ON COLUMN "File"."Extension" IS '';
COMMENT ON COLUMN "File"."Url" IS '';
COMMENT ON COLUMN "File"."Path" IS '';
COMMENT ON COLUMN "File"."StorageType" IS '';
COMMENT ON COLUMN "File"."ContentType" IS '';
COMMENT ON COLUMN "File"."Hash" IS '';
COMMENT ON COLUMN "File"."OriginalId" IS '';
COMMENT ON COLUMN "File"."State" IS '';
COMMENT ON COLUMN "File"."IsDeleted" IS '';
COMMENT ON COLUMN "File"."CreatedAt" IS '';
COMMENT ON COLUMN "File"."CreatedBy" IS '';
COMMENT ON COLUMN "File"."UpdatedAt" IS '';
COMMENT ON COLUMN "File"."UpdatedBy" IS '';
COMMENT ON COLUMN "File"."Remark" IS '';

CREATE TABLE "GlobalSettings" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "AppId" bigint NOT NULL,
    "Key" character varying(128) NOT NULL,
    "ConfigurationJson" text,
    "IsDeleted" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedBy" bigint,
    "Remark" text,
    CONSTRAINT "PK_GlobalSettings" PRIMARY KEY ("Id")
);
COMMENT ON TABLE "GlobalSettings" IS '';
COMMENT ON COLUMN "GlobalSettings"."Id" IS '';
COMMENT ON COLUMN "GlobalSettings"."AppId" IS '';
COMMENT ON COLUMN "GlobalSettings"."Key" IS '';
COMMENT ON COLUMN "GlobalSettings"."ConfigurationJson" IS '';
COMMENT ON COLUMN "GlobalSettings"."IsDeleted" IS '';
COMMENT ON COLUMN "GlobalSettings"."CreatedAt" IS '';
COMMENT ON COLUMN "GlobalSettings"."CreatedBy" IS '';
COMMENT ON COLUMN "GlobalSettings"."UpdatedAt" IS '';
COMMENT ON COLUMN "GlobalSettings"."UpdatedBy" IS '';
COMMENT ON COLUMN "GlobalSettings"."Remark" IS '';

CREATE TABLE "Menu" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(256) NOT NULL,
    "Code" character varying(256) NOT NULL,
    "ParentId" bigint NOT NULL,
    "Type" integer NOT NULL,
    "PlatformType" integer NOT NULL,
    "Icon" character varying(1024),
    "IconType" integer NOT NULL,
    "ActiveIcon" character varying(1024),
    "ActiveIconType" integer NOT NULL,
    "Url" character varying(1024),
    "Order" integer NOT NULL,
    "IsVisible" boolean NOT NULL,
    "IsExternalLink" boolean NOT NULL,
    "IdSequences" text NOT NULL,
    "SystemId" bigint NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedBy" bigint,
    "Remark" text,
    CONSTRAINT "PK_Menu" PRIMARY KEY ("Id")
);
COMMENT ON TABLE "Menu" IS '';
COMMENT ON COLUMN "Menu"."Id" IS '';
COMMENT ON COLUMN "Menu"."Name" IS '';
COMMENT ON COLUMN "Menu"."Code" IS '';
COMMENT ON COLUMN "Menu"."ParentId" IS '';
COMMENT ON COLUMN "Menu"."Type" IS '';
COMMENT ON COLUMN "Menu"."PlatformType" IS '';
COMMENT ON COLUMN "Menu"."Icon" IS '';
COMMENT ON COLUMN "Menu"."IconType" IS '';
COMMENT ON COLUMN "Menu"."ActiveIcon" IS '';
COMMENT ON COLUMN "Menu"."ActiveIconType" IS '';
COMMENT ON COLUMN "Menu"."Url" IS '';
COMMENT ON COLUMN "Menu"."Order" IS '';
COMMENT ON COLUMN "Menu"."IsVisible" IS '';
COMMENT ON COLUMN "Menu"."IsExternalLink" IS '';
COMMENT ON COLUMN "Menu"."IdSequences" IS '';
COMMENT ON COLUMN "Menu"."SystemId" IS '';
COMMENT ON COLUMN "Menu"."IsDeleted" IS '';
COMMENT ON COLUMN "Menu"."CreatedAt" IS '';
COMMENT ON COLUMN "Menu"."CreatedBy" IS '';
COMMENT ON COLUMN "Menu"."UpdatedAt" IS '';
COMMENT ON COLUMN "Menu"."UpdatedBy" IS '';
COMMENT ON COLUMN "Menu"."Remark" IS '';

CREATE TABLE "OperationLog" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "IpAddress" character varying(128),
    "LogType" integer NOT NULL,
    "UserAgent" character varying(512),
    "OperationContent" text NOT NULL,
    "MenuCode" character varying(128) NOT NULL,
    "ErrorTracker" text,
    "OperationMenu" text NOT NULL,
    "Method" text NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedBy" bigint,
    "Remark" text,
    CONSTRAINT "PK_OperationLog" PRIMARY KEY ("Id")
);
COMMENT ON TABLE "OperationLog" IS '';
COMMENT ON COLUMN "OperationLog"."Id" IS '';
COMMENT ON COLUMN "OperationLog"."IpAddress" IS '';
COMMENT ON COLUMN "OperationLog"."LogType" IS '';
COMMENT ON COLUMN "OperationLog"."UserAgent" IS '';
COMMENT ON COLUMN "OperationLog"."OperationContent" IS '';
COMMENT ON COLUMN "OperationLog"."MenuCode" IS '';
COMMENT ON COLUMN "OperationLog"."ErrorTracker" IS '';
COMMENT ON COLUMN "OperationLog"."OperationMenu" IS '';
COMMENT ON COLUMN "OperationLog"."Method" IS '';
COMMENT ON COLUMN "OperationLog"."IsDeleted" IS '';
COMMENT ON COLUMN "OperationLog"."CreatedAt" IS '';
COMMENT ON COLUMN "OperationLog"."CreatedBy" IS '';
COMMENT ON COLUMN "OperationLog"."UpdatedAt" IS '';
COMMENT ON COLUMN "OperationLog"."UpdatedBy" IS '';
COMMENT ON COLUMN "OperationLog"."Remark" IS '';

CREATE TABLE "Region" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(64) NOT NULL,
    "ShortName" character varying(64) NOT NULL,
    "Code" character varying(64) NOT NULL,
    "ParentId" bigint NOT NULL,
    "Level" integer NOT NULL,
    "Order" integer NOT NULL,
    "IdSequences" text NOT NULL,
    "IsEnable" boolean NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedBy" bigint,
    "Remark" text,
    CONSTRAINT "PK_Region" PRIMARY KEY ("Id")
);
COMMENT ON TABLE "Region" IS '';
COMMENT ON COLUMN "Region"."Id" IS '';
COMMENT ON COLUMN "Region"."Name" IS '';
COMMENT ON COLUMN "Region"."ShortName" IS '';
COMMENT ON COLUMN "Region"."Code" IS '';
COMMENT ON COLUMN "Region"."ParentId" IS '';
COMMENT ON COLUMN "Region"."Level" IS '';
COMMENT ON COLUMN "Region"."Order" IS '';
COMMENT ON COLUMN "Region"."IdSequences" IS '';
COMMENT ON COLUMN "Region"."IsEnable" IS '';
COMMENT ON COLUMN "Region"."IsDeleted" IS '';
COMMENT ON COLUMN "Region"."CreatedAt" IS '';
COMMENT ON COLUMN "Region"."CreatedBy" IS '';
COMMENT ON COLUMN "Region"."UpdatedAt" IS '';
COMMENT ON COLUMN "Region"."UpdatedBy" IS '';
COMMENT ON COLUMN "Region"."Remark" IS '';

CREATE TABLE "Role" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(64) NOT NULL,
    "Platforms" integer NOT NULL,
    "Code" character varying(64) NOT NULL,
    "IsSystem" boolean NOT NULL,
    "Order" integer NOT NULL,
    "IsEnable" boolean NOT NULL,
    "SystemId" bigint NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedBy" bigint,
    "Remark" text,
    CONSTRAINT "PK_Role" PRIMARY KEY ("Id")
);
COMMENT ON TABLE "Role" IS '';
COMMENT ON COLUMN "Role"."Id" IS '';
COMMENT ON COLUMN "Role"."Name" IS '';
COMMENT ON COLUMN "Role"."Platforms" IS '';
COMMENT ON COLUMN "Role"."Code" IS '';
COMMENT ON COLUMN "Role"."IsSystem" IS '';
COMMENT ON COLUMN "Role"."Order" IS '';
COMMENT ON COLUMN "Role"."IsEnable" IS '';
COMMENT ON COLUMN "Role"."SystemId" IS '';
COMMENT ON COLUMN "Role"."IsDeleted" IS '';
COMMENT ON COLUMN "Role"."CreatedAt" IS '';
COMMENT ON COLUMN "Role"."CreatedBy" IS '';
COMMENT ON COLUMN "Role"."UpdatedAt" IS '';
COMMENT ON COLUMN "Role"."UpdatedBy" IS '';
COMMENT ON COLUMN "Role"."Remark" IS '';

CREATE TABLE "ScheduleTask" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(256) NOT NULL,
    "Code" character varying(256),
    "IsEnable" boolean NOT NULL,
    "Expression" text,
    "NextExecuteTime" timestamp with time zone NOT NULL,
    "LastExecuteTime" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_ScheduleTask" PRIMARY KEY ("Id")
);
COMMENT ON TABLE "ScheduleTask" IS '';
COMMENT ON COLUMN "ScheduleTask"."Id" IS '';
COMMENT ON COLUMN "ScheduleTask"."Name" IS '';
COMMENT ON COLUMN "ScheduleTask"."Code" IS '';
COMMENT ON COLUMN "ScheduleTask"."IsEnable" IS '';
COMMENT ON COLUMN "ScheduleTask"."Expression" IS '';
COMMENT ON COLUMN "ScheduleTask"."NextExecuteTime" IS '';
COMMENT ON COLUMN "ScheduleTask"."LastExecuteTime" IS '';
COMMENT ON COLUMN "ScheduleTask"."IsDeleted" IS '';

CREATE TABLE "SeedDataTask" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "LastWriteTime" timestamp with time zone NOT NULL,
    "Name" character varying(256) NOT NULL,
    "Code" character varying(256),
    "IsEnable" boolean NOT NULL,
    "ExecuteTime" timestamp with time zone NOT NULL,
    "ExecuteStatus" integer NOT NULL,
    "ConfigPath" text,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_SeedDataTask" PRIMARY KEY ("Id")
);
COMMENT ON TABLE "SeedDataTask" IS '';
COMMENT ON COLUMN "SeedDataTask"."Id" IS '';
COMMENT ON COLUMN "SeedDataTask"."LastWriteTime" IS '';
COMMENT ON COLUMN "SeedDataTask"."Name" IS '';
COMMENT ON COLUMN "SeedDataTask"."Code" IS '';
COMMENT ON COLUMN "SeedDataTask"."IsEnable" IS '';
COMMENT ON COLUMN "SeedDataTask"."ExecuteTime" IS '';
COMMENT ON COLUMN "SeedDataTask"."ExecuteStatus" IS '';
COMMENT ON COLUMN "SeedDataTask"."ConfigPath" IS '';
COMMENT ON COLUMN "SeedDataTask"."IsDeleted" IS '';

CREATE TABLE "User" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Mobile" character varying(15),
    "RealName" character varying(128),
    "UserName" character varying(128) NOT NULL,
    "NickName" character varying(128),
    "Password" character varying(256) NOT NULL,
    "PasswordSalt" character varying(256) NOT NULL,
    "IsEnable" boolean NOT NULL,
    "Gender" integer NOT NULL,
    "Avatar" character varying(512),
    "Email" character varying(120) NOT NULL,
    "LastLoginTime" timestamp with time zone NOT NULL,
    "SignatureUrl" character varying(512),
    "IsDeleted" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedBy" bigint,
    "Remark" text,
    CONSTRAINT "PK_User" PRIMARY KEY ("Id")
);
COMMENT ON TABLE "User" IS '';
COMMENT ON COLUMN "User"."Id" IS '';
COMMENT ON COLUMN "User"."Mobile" IS '';
COMMENT ON COLUMN "User"."RealName" IS '';
COMMENT ON COLUMN "User"."UserName" IS '';
COMMENT ON COLUMN "User"."NickName" IS '';
COMMENT ON COLUMN "User"."Password" IS '';
COMMENT ON COLUMN "User"."PasswordSalt" IS '';
COMMENT ON COLUMN "User"."IsEnable" IS '';
COMMENT ON COLUMN "User"."Gender" IS '';
COMMENT ON COLUMN "User"."Avatar" IS '';
COMMENT ON COLUMN "User"."Email" IS '';
COMMENT ON COLUMN "User"."LastLoginTime" IS '';
COMMENT ON COLUMN "User"."SignatureUrl" IS '';
COMMENT ON COLUMN "User"."IsDeleted" IS '';
COMMENT ON COLUMN "User"."CreatedAt" IS '';
COMMENT ON COLUMN "User"."CreatedBy" IS '';
COMMENT ON COLUMN "User"."UpdatedAt" IS '';
COMMENT ON COLUMN "User"."UpdatedBy" IS '';
COMMENT ON COLUMN "User"."Remark" IS '';

CREATE TABLE "MenuResource" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "MenuId" bigint NOT NULL,
    "ApiResourceId" bigint NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedBy" bigint,
    "Remark" text,
    CONSTRAINT "PK_MenuResource" PRIMARY KEY ("Id")
);
COMMENT ON TABLE "MenuResource" IS '';
COMMENT ON COLUMN "MenuResource"."Id" IS '';
COMMENT ON COLUMN "MenuResource"."MenuId" IS '';
COMMENT ON COLUMN "MenuResource"."ApiResourceId" IS '';
COMMENT ON COLUMN "MenuResource"."IsDeleted" IS '';
COMMENT ON COLUMN "MenuResource"."CreatedAt" IS '';
COMMENT ON COLUMN "MenuResource"."CreatedBy" IS '';
COMMENT ON COLUMN "MenuResource"."UpdatedAt" IS '';
COMMENT ON COLUMN "MenuResource"."UpdatedBy" IS '';
COMMENT ON COLUMN "MenuResource"."Remark" IS '';

CREATE TABLE "Permission" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" bigint NOT NULL,
    "MenuId" bigint NOT NULL,
    "DataRange" integer NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedBy" bigint,
    "Remark" text,
    CONSTRAINT "PK_Permission" PRIMARY KEY ("Id")
);
COMMENT ON TABLE "Permission" IS '';
COMMENT ON COLUMN "Permission"."Id" IS '';
COMMENT ON COLUMN "Permission"."RoleId" IS '';
COMMENT ON COLUMN "Permission"."MenuId" IS '';
COMMENT ON COLUMN "Permission"."DataRange" IS '';
COMMENT ON COLUMN "Permission"."IsDeleted" IS '';
COMMENT ON COLUMN "Permission"."CreatedAt" IS '';
COMMENT ON COLUMN "Permission"."CreatedBy" IS '';
COMMENT ON COLUMN "Permission"."UpdatedAt" IS '';
COMMENT ON COLUMN "Permission"."UpdatedBy" IS '';
COMMENT ON COLUMN "Permission"."Remark" IS '';

CREATE TABLE "ScheduleTaskRecord" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ScheduleTaskId" bigint NOT NULL,
    "IsSuccess" boolean NOT NULL,
    "ErrorMessage" text,
    "ExecuteStartTime" timestamp with time zone NOT NULL,
    "ExpressionTime" timestamp with time zone NOT NULL,
    "ExecuteEndTime" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_ScheduleTaskRecord" PRIMARY KEY ("Id")
);
COMMENT ON TABLE "ScheduleTaskRecord" IS '';
COMMENT ON COLUMN "ScheduleTaskRecord"."Id" IS '';
COMMENT ON COLUMN "ScheduleTaskRecord"."ScheduleTaskId" IS '';
COMMENT ON COLUMN "ScheduleTaskRecord"."IsSuccess" IS '';
COMMENT ON COLUMN "ScheduleTaskRecord"."ErrorMessage" IS '';
COMMENT ON COLUMN "ScheduleTaskRecord"."ExecuteStartTime" IS '';
COMMENT ON COLUMN "ScheduleTaskRecord"."ExpressionTime" IS '';
COMMENT ON COLUMN "ScheduleTaskRecord"."ExecuteEndTime" IS '';
COMMENT ON COLUMN "ScheduleTaskRecord"."IsDeleted" IS '';

CREATE TABLE "UserDepartment" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "UserId" bigint NOT NULL,
    "DepartmentId" bigint NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedBy" bigint,
    "Remark" text,
    CONSTRAINT "PK_UserDepartment" PRIMARY KEY ("Id")
);
COMMENT ON TABLE "UserDepartment" IS '';
COMMENT ON COLUMN "UserDepartment"."Id" IS '';
COMMENT ON COLUMN "UserDepartment"."UserId" IS '';
COMMENT ON COLUMN "UserDepartment"."DepartmentId" IS '';
COMMENT ON COLUMN "UserDepartment"."IsDeleted" IS '';
COMMENT ON COLUMN "UserDepartment"."CreatedAt" IS '';
COMMENT ON COLUMN "UserDepartment"."CreatedBy" IS '';
COMMENT ON COLUMN "UserDepartment"."UpdatedAt" IS '';
COMMENT ON COLUMN "UserDepartment"."UpdatedBy" IS '';
COMMENT ON COLUMN "UserDepartment"."Remark" IS '';

CREATE TABLE "UserRole" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "UserId" bigint NOT NULL,
    "RoleId" bigint NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedBy" bigint,
    "Remark" text,
    CONSTRAINT "PK_UserRole" PRIMARY KEY ("Id")
);
COMMENT ON TABLE "UserRole" IS '';
COMMENT ON COLUMN "UserRole"."Id" IS '';
COMMENT ON COLUMN "UserRole"."UserId" IS '';
COMMENT ON COLUMN "UserRole"."RoleId" IS '';
COMMENT ON COLUMN "UserRole"."IsDeleted" IS '';
COMMENT ON COLUMN "UserRole"."CreatedAt" IS '';
COMMENT ON COLUMN "UserRole"."CreatedBy" IS '';
COMMENT ON COLUMN "UserRole"."UpdatedAt" IS '';
COMMENT ON COLUMN "UserRole"."UpdatedBy" IS '';
COMMENT ON COLUMN "UserRole"."Remark" IS '';

CREATE TABLE "UserToken" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "UserId" bigint NOT NULL,
    "Token" character varying(256) NOT NULL,
    "TokenHash" character varying(32) NOT NULL,
    "RefreshToken" character varying(256) NOT NULL,
    "ExpirationDate" timestamp with time zone NOT NULL,
    "IpAddress" character varying(32) NOT NULL,
    "UserAgent" character varying(1024) NOT NULL,
    "PlatformType" integer NOT NULL,
    "LoginMethodType" integer NOT NULL,
    "RefreshTokenIsAvailable" boolean NOT NULL,
    "LoginType" integer NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedBy" bigint,
    "Remark" text,
    CONSTRAINT "PK_UserToken" PRIMARY KEY ("Id")
);
COMMENT ON TABLE "UserToken" IS '';
COMMENT ON COLUMN "UserToken"."Id" IS '';
COMMENT ON COLUMN "UserToken"."UserId" IS '';
COMMENT ON COLUMN "UserToken"."Token" IS '';
COMMENT ON COLUMN "UserToken"."TokenHash" IS '';
COMMENT ON COLUMN "UserToken"."RefreshToken" IS '';
COMMENT ON COLUMN "UserToken"."ExpirationDate" IS '';
COMMENT ON COLUMN "UserToken"."IpAddress" IS '';
COMMENT ON COLUMN "UserToken"."UserAgent" IS '';
COMMENT ON COLUMN "UserToken"."PlatformType" IS '';
COMMENT ON COLUMN "UserToken"."LoginMethodType" IS '';
COMMENT ON COLUMN "UserToken"."RefreshTokenIsAvailable" IS '';
COMMENT ON COLUMN "UserToken"."LoginType" IS '';
COMMENT ON COLUMN "UserToken"."IsDeleted" IS '';
COMMENT ON COLUMN "UserToken"."CreatedAt" IS '';
COMMENT ON COLUMN "UserToken"."CreatedBy" IS '';
COMMENT ON COLUMN "UserToken"."UpdatedAt" IS '';
COMMENT ON COLUMN "UserToken"."UpdatedBy" IS '';
COMMENT ON COLUMN "UserToken"."Remark" IS '';

CREATE INDEX "IX_Menu_ParentId" ON "Menu" ("ParentId");

CREATE INDEX "IX_MenuResource_ApiResourceId" ON "MenuResource" ("ApiResourceId");

CREATE INDEX "IX_MenuResource_MenuId" ON "MenuResource" ("MenuId");

CREATE INDEX "IX_Permission_MenuId" ON "Permission" ("MenuId");

CREATE INDEX "IX_Permission_RoleId" ON "Permission" ("RoleId");

CREATE INDEX "IX_ScheduleTaskRecord_ScheduleTaskId" ON "ScheduleTaskRecord" ("ScheduleTaskId");

CREATE INDEX "IX_UserDepartment_DepartmentId" ON "UserDepartment" ("DepartmentId");

CREATE INDEX "IX_UserDepartment_UserId" ON "UserDepartment" ("UserId");

CREATE INDEX "IX_UserRole_RoleId" ON "UserRole" ("RoleId");

CREATE INDEX "IX_UserRole_UserId" ON "UserRole" ("UserId");

CREATE INDEX "IX_UserToken_UserId" ON "UserToken" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260307033208_InitialDatabase', '10.0.7');

COMMIT;

