// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexusStack.EFCore.DbContexts;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NexusStack.WebAPI.Migrations
{
    [DbContext(typeof(MainContext))]
    partial class MainContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NexusStack.Core.Entities.AsyncTasks.AsyncTask", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<string>("Result")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.HasKey("Id");

                    b.ToTable("AsyncTask", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("NexusStack.Core.Entities.Messages.InternalMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Attachments")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<int>("MessageType")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.Property<int>("Platforms")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.HasKey("Id");

                    b.ToTable("InternalMessage", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("NexusStack.Core.Entities.Messages.InternalMessageRecipient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<long?>("RecipientUserId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.ToTable("InternalMessageRecipient", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("NexusStack.Core.Entities.Messages.NotifyEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<int>("EventType")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<string>("MessageTypes")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasComment("");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<string>("NotifyRoles")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasComment("");

                    b.Property<int?>("Order")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("NotifyEvent", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("NexusStack.Core.Entities.Messages.SMSMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BizId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<int>("MessageStatus")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.Property<int>("MessageType")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.Property<long>("Recipient")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.HasKey("Id");

                    b.ToTable("SMSMessage", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("NexusStack.Core.Entities.OpenAppConfig.AppConfig", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AccessToken")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<long?>("AccessValidTime")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("AppKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<string>("SecretKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<string>("Sessionkey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.HasKey("Id");

                    b.ToTable("AppConfig", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("NexusStack.Core.Entities.OpenAppConfigs.AppEventConfig", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AppId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("EventCode")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<string>("HookUrl")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<string>("Method")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.HasKey("Id");

                    b.ToTable("AppEventConfig", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("NexusStack.Core.Entities.OpenAppConfigs.AppNotificationConfig", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AppId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<string>("NoticeUrl")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<string>("Phones")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.HasKey("Id");

                    b.ToTable("AppNotificationConfig", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("NexusStack.Core.Entities.OpenAppConfigs.AppWebhookConfig", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AppId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("HookUrl")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<string>("Method")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.HasKey("Id");

                    b.ToTable("AppWebhookConfig", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("NexusStack.Core.Entities.Schedules.ScheduleTask", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<string>("Expression")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<bool>("IsEnable")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<DateTime>("LastExecuteTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<DateTime>("NextExecuteTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.HasKey("Id");

                    b.ToTable("ScheduleTask", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("NexusStack.Core.Entities.Schedules.ScheduleTaskRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<DateTime>("ExecuteEndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<DateTime>("ExecuteStartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<DateTime>("ExpressionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<long>("ScheduleTaskId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleTaskId");

                    b.ToTable("ScheduleTaskRecord", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("NexusStack.Core.Entities.Schedules.SeedDataTask", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<string>("ConfigPath")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<int>("ExecuteStatus")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.Property<DateTime>("ExecuteTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<bool>("IsEnable")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<DateTime>("LastWriteTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.HasKey("Id");

                    b.ToTable("SeedDataTask", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("NexusStack.Core.Entities.SystemManagement.ApiResource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActionName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<string>("Code")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<string>("ControllerName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("GroupName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<string>("NameSpace")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<string>("RequestMethod")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<string>("RoutePattern")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.HasKey("Id");

                    b.ToTable("ApiResource", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("NexusStack.Core.Entities.SystemManagement.DownloadItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.Property<int>("StorageType")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("bucket")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<string>("key")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.HasKey("Id");

                    b.ToTable("DownloadItem", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("NexusStack.Core.Entities.SystemManagement.File", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasComment("");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<long>("OriginalId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasComment("");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.Property<int>("StorageType")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasComment("");

                    b.HasKey("Id");

                    b.ToTable("File", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("NexusStack.Core.Entities.SystemManagement.GlobalSettings", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AppId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("ConfigurationJson")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.HasKey("Id");

                    b.ToTable("GlobalSettings", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("NexusStack.Core.Entities.SystemManagement.Menu", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActiveIcon")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasComment("");

                    b.Property<int>("ActiveIconType")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("Icon")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasComment("");

                    b.Property<int>("IconType")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.Property<string>("IdSequences")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<bool>("IsExternalLink")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<int>("PlatformType")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<long>("SystemId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("Url")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasComment("");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Menu", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("NexusStack.Core.Entities.SystemManagement.MenuResource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ApiResourceId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<long>("MenuId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.HasKey("Id");

                    b.HasIndex("ApiResourceId");

                    b.HasIndex("MenuId");

                    b.ToTable("MenuResource", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("NexusStack.Core.Entities.SystemManagement.OperationLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("ErrorTracker")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<int>("LogType")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.Property<string>("MenuCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("");

                    b.Property<string>("Method")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<string>("OperationContent")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<string>("OperationMenu")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasComment("");

                    b.HasKey("Id");

                    b.ToTable("OperationLog", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("NexusStack.Core.Entities.SystemManagement.Options", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasComment("");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<long>("SystemId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("");

                    b.HasKey("Id");

                    b.ToTable("Options", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("NexusStack.Core.Entities.SystemManagement.Region", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("IdSequences")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<bool>("IsEnable")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.HasKey("Id");

                    b.ToTable("Region", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("NexusStack.Core.Entities.Users.Permission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<int>("DataRange")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<long>("MenuId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("RoleId");

                    b.ToTable("Permission", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("NexusStack.Core.Entities.Users.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<bool>("IsEnable")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.Property<int>("Platforms")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<long>("SystemId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.HasKey("Id");

                    b.ToTable("Role", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("NexusStack.Core.Entities.Users.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Avatar")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasComment("");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasComment("");

                    b.Property<int>("Gender")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<bool>("IsEnable")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<DateTime>("LastLoginTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<string>("Mobile")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasComment("");

                    b.Property<string>("NickName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<string>("RealName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<string>("SignatureUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasComment("");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("");

                    b.HasKey("Id");

                    b.ToTable("User", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("NexusStack.Core.Entities.Users.UserDepartment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<long>("DepartmentId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId");

                    b.ToTable("UserDepartment", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("NexusStack.Core.Entities.Users.UserRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRole", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("NexusStack.Core.Entities.Users.UserToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<int>("LoginMethodType")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.Property<int>("LoginType")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.Property<int>("PlatformType")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<bool>("RefreshTokenIsAvailable")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasComment("");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasComment("");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserToken", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("NexusStack.Core.Entities.Messages.InternalMessageRecipient", b =>
                {
                    b.HasOne("NexusStack.Core.Entities.Messages.InternalMessage", "Message")
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("NexusStack.Core.Entities.Messages.NotifyEvent", b =>
                {
                    b.HasOne("NexusStack.Core.Entities.Messages.NotifyEvent", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("NexusStack.Core.Entities.Schedules.ScheduleTaskRecord", b =>
                {
                    b.HasOne("NexusStack.Core.Entities.Schedules.ScheduleTask", "ScheduleTask")
                        .WithMany()
                        .HasForeignKey("ScheduleTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ScheduleTask");
                });

            modelBuilder.Entity("NexusStack.Core.Entities.SystemManagement.Menu", b =>
                {
                    b.HasOne("NexusStack.Core.Entities.SystemManagement.Menu", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("NexusStack.Core.Entities.SystemManagement.MenuResource", b =>
                {
                    b.HasOne("NexusStack.Core.Entities.SystemManagement.ApiResource", "ApiResource")
                        .WithMany()
                        .HasForeignKey("ApiResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexusStack.Core.Entities.SystemManagement.Menu", "Menu")
                        .WithMany("Resources")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApiResource");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("NexusStack.Core.Entities.Users.Permission", b =>
                {
                    b.HasOne("NexusStack.Core.Entities.SystemManagement.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexusStack.Core.Entities.Users.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("NexusStack.Core.Entities.Users.UserDepartment", b =>
                {
                    b.HasOne("NexusStack.Core.Entities.SystemManagement.Region", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexusStack.Core.Entities.Users.User", "User")
                        .WithMany("UserDepartments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NexusStack.Core.Entities.Users.UserRole", b =>
                {
                    b.HasOne("NexusStack.Core.Entities.Users.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexusStack.Core.Entities.Users.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NexusStack.Core.Entities.Users.UserToken", b =>
                {
                    b.HasOne("NexusStack.Core.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NexusStack.Core.Entities.Messages.NotifyEvent", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("NexusStack.Core.Entities.SystemManagement.Menu", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Resources");
                });

            modelBuilder.Entity("NexusStack.Core.Entities.Users.Role", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("NexusStack.Core.Entities.Users.User", b =>
                {
                    b.Navigation("UserDepartments");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
